### ISSUE TITLE
jenkins.model.InvalidBuildsDir:

### ISSUE THREAD

**Issue by rajeshgond008** [ros-industrial-attic/jenkins_config#24]
sudo service jenkins stop
sudo mv /var/lib/jenkins /home
sudo ln -s /home/jenkins /var/lib/jenkins
sudo service jenkins start
### 
### **After changing home directory of jenkins its given below error**

 Error
jenkins.model.InvalidBuildsDir: ${ITEM_ROOTDIR}/builds does not exist and probably cannot be created
	at jenkins.model.Jenkins.checkRawBuildsDir(Jenkins.java:3087)
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3011)
Caused: java.io.IOException
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3014)
	at jenkins.model.Jenkins.access$1300(Jenkins.java:304)
	at jenkins.model.Jenkins$13.run(Jenkins.java:3106)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1102)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)

**Comment by rajeshgond008** [comment]
Please help me ...

**Comment by gavanderhoorn** [comment]
I'm not sure if this is the right place to ask for help:

 - this repository has no relation to Jenkins itself at all, so if you're looking for support with Jenkins itself this is not where you should be looking
 - the content in this repository is at least 4 years old and is no longer being used
 - if you are looking to setup a ROS buildfarm (for CI or other purposes) then I would recommend to ask your question on ROS Answers
 - if you are having a problem while setting up a ROS buildfarm I suggest to ask your question on any of the `ros_buildfarm` trackers
 - if you are trying to use the configuration in this repository I would advise against it: there are better tools/configurations now (such as the ROS buildfarm)

and so on.

I'm going to close this for now, but if you feel that is not correct, please re-open and provide additional context so that we can understand what you're actually trying to do.

Do feel free to keep commenting on the issue btw.
